name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for file in $(find . -name "*.html" -not -path "./.git/*"); do
            url="https://www.authormiracross.com${file#./}"
            url=${url/index.html/}
            echo "  <url><loc>$url</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit & Push Sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-generate sitemap"
          git push
